PREAMBLE = """# Auto generated file.
# This file was automatically generated by https://github.com/symonk/pycdp
# inline with the cdp specification for version {}.
#
# Please update the generator code to make changes here.
"""
